
security:
    providers:
        chain_provider:
            chain:
                providers: [db_username, db_email]
        db_username:
            entity:
                class: AppBundle\Entity\User
                property: username
        db_email:
            entity:
                class: AppBundle\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: login[username]
                password_parameter: login[password]
            anonymous: ~
            logout:
                path:   /logout
                target: /

                
    encoders:
        AppBundle\Entity\User: plaintext


